// js/testapps/agents-angular/src/app/pages/weather-chat.component.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

import { Component, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { injectGenkitAgent } from '../genkit-angular';

interface DisplayRow {
  role: 'user' | 'model' | 'tool';
  text: string;
}

@Component({
  selector: 'app-weather-chat',
  imports: [FormsModule],
  template: `
    <h2>Weather agent</h2>
    <p class="desc">
      Multi-turn chat with tool calling. Same backend
      (<code>/api/weatherAgent</code>) as the React testapp.
    </p>

    @for (m of displayed(); track $index) {
      <div class="msg msg-{{ m.role }}">
        <span class="role">{{ m.role }}</span>
        <span class="text">{{ m.text }}</span>
      </div>
    }

    @if (state().streamingText) {
      <div class="msg msg-model streaming">
        <span class="role">model</span>
        <span class="text">{{ state().streamingText }}<span class="cursor">▊</span></span>
      </div>
    }

    @if (state().phase === 'streaming' && !state().streamingText) {
      <div class="msg msg-system">
        <span class="text">Thinking…</span>
      </div>
    }

    <form class="composer" (submit)="onSubmit($event)">
      <input
        type="text"
        [(ngModel)]="draft"
        name="draft"
        [disabled]="state().phase === 'streaming'"
        placeholder="Ask about the weather…" />
      <button type="submit" [disabled]="!draft() || state().phase === 'streaming'">
        Send
      </button>
    </form>

    <div class="suggestions">
      @for (s of suggestions; track s) {
        <button class="chip" (click)="ask(s)">{{ s }}</button>
      }
    </div>
  `,
  styles: [`
    h2 { margin: 0 0 4px; }
    .desc { color: #667085; font-size: 13px; margin: 0 0 20px; }
    .msg { padding: 10px 14px; border-radius: 8px; margin: 8px 0; max-width: 720px; background: #fff; border: 1px solid #e4e7ec; }
    .role { font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #98a2b3; margin-right: 8px; }
    .text { white-space: pre-wrap; }
    .msg-user { background: #eaf0ff; border-color: #cdddff; }
    .msg-tool { background: #f1f5f9; font-family: ui-monospace, monospace; font-size: 13px; }
    .msg-system { color: #667085; font-style: italic; }
    .streaming .cursor { animation: blink 1s steps(2) infinite; }
    @keyframes blink { 50% { opacity: 0; } }
    .composer { display: flex; gap: 8px; margin: 20px 0; }
    .composer input { flex: 1; padding: 10px 12px; border-radius: 8px; border: 1px solid #cdd5e0; font-size: 14px; }
    .composer button { padding: 0 16px; border-radius: 8px; border: 0; background: #3158d6; color: #fff; font-weight: 600; cursor: pointer; }
    .composer button:disabled { background: #98a2b3; cursor: not-allowed; }
    .suggestions { display: flex; gap: 8px; flex-wrap: wrap; }
    .chip { padding: 6px 12px; border-radius: 999px; border: 1px solid #d0d5dd; background: #fff; cursor: pointer; font-size: 13px; }
    .chip:hover { background: #f1f5f9; }
  `],
})
export class WeatherChatComponent {
  readonly draft = signal('');
  readonly suggestions = [
    'What is the weather like in London?',
    'Is it sunny in Tokyo right now?',
    'Compare the weather in Paris and New York.',
  ];

  private readonly agent = injectGenkitAgent({ url: '/api/weatherAgent' });
  readonly state = this.agent.state;

  // Project agent.messages + in-flight toolCalls into the display rows.
  readonly displayed = computed<DisplayRow[]>(() => {
    const out: DisplayRow[] = [];
    for (const m of this.state().messages) {
      const role = m.role as DisplayRow['role'];
      const textParts = (m.content || [])
        .filter((p) => p['text'])
        .map((p) => String(p['text']))
        .join('');
      if (textParts) out.push({ role, text: textParts });
      for (const p of m.content || []) {
        if (p.toolRequest) {
          out.push({
            role: 'tool',
            text: `🔧 ${p.toolRequest.name}(${JSON.stringify(p.toolRequest.input)})`,
          });
        }
        if (p.toolResponse) {
          out.push({
            role: 'tool',
            text: `✅ ${p.toolResponse.name} → ${JSON.stringify(p.toolResponse.output)}`,
          });
        }
      }
    }
    // Live tool calls during streaming.
    if (this.state().phase === 'streaming') {
      for (const tc of this.state().toolCalls) {
        if (tc.state === 'call') {
          out.push({ role: 'tool', text: `🔧 Calling ${tc.name}…` });
        } else if (tc.state === 'error') {
          out.push({
            role: 'tool',
            text: `❌ ${tc.name} failed: ${tc.errorText ?? ''}`,
          });
        }
      }
    }
    return out;
  });

  ask(text: string) {
    this.agent.submit({
      messages: [{ role: 'user', content: [{ text }] }],
    });
  }

  onSubmit(e: Event) {
    e.preventDefault();
    const text = this.draft().trim();
    if (!text) return;
    this.draft.set('');
    this.ask(text);
  }
}

// js/testapps/agents/web/src/pages/WeatherChat.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { useCallback, useEffect, useMemo } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ChatUI, type ChatMessage } from '../components/ChatUI';
import { useGenkitAgent } from '../genkit-react';

// ---------------------------------------------------------------------------
// Weather Chat — MIGRATED TO v2 HOOKS
//
// Before: 345 LOC managing streamFlow, stateRef, snapshotIdRef, restoration,
// chunk parsing, tool rendering, and URL updates by hand.
//
// After: ~130 LOC of UI. All wire-protocol concerns absorbed by
// `useGenkitAgent`:
//   - continuationId opaque-token round-tripping (no state/snapshotId fork)
//   - URL-bookmark restoration via `resumeFromContinuation`
//   - walkAgentEvent dispatch — text, tool calls, tool responses
//   - committed message history + in-flight streaming text
// ---------------------------------------------------------------------------

const ENDPOINT = '/api/weatherAgent';

export default function WeatherChat() {
  const { snapshotId: urlSnapshotId } = useParams<{ snapshotId: string }>();
  const navigate = useNavigate();

  const agent = useGenkitAgent({
    url: ENDPOINT,
    resumeFromSnapshotId: urlSnapshotId,
  });

  // Push the snapshot back to the URL when it changes (bookmarkable).
  useEffect(() => {
    if (!agent.snapshotId || agent.snapshotId === urlSnapshotId) return;
    navigate(`/weather/${agent.snapshotId}`, { replace: true });
  }, [agent.snapshotId, urlSnapshotId, navigate]);

  const handleSend = useCallback(
    (text: string) => {
      if (agent.phase === 'streaming') return;
      agent.submit({ messages: [{ role: 'user', content: [{ text }] }] });
    },
    [agent]
  );

  // Project the hook's reactive state into the ChatUI's message format.
  const chatMessages = useMemo<ChatMessage[]>(() => {
    return agent.messages.flatMap((msg) =>
      messageToChatRows(msg as { role: string; content?: any[] })
    );
  }, [agent.messages]);

  const inFlightRows = useMemo<ChatMessage[]>(() => {
    const rows: ChatMessage[] = [];
    for (const tc of agent.toolCalls) {
      if (tc.state === 'call') {
        rows.push({
          role: 'tool',
          text: `🔧 Calling ${tc.name}(${JSON.stringify(tc.input)})`,
        });
      } else if (tc.state === 'result') {
        rows.push({
          role: 'tool',
          text: `✅ ${tc.name} → ${JSON.stringify(tc.output)}`,
        });
      } else {
        rows.push({ role: 'tool', text: `❌ ${tc.name} failed` });
      }
    }
    return rows;
  }, [agent.toolCalls]);

  return (
    <div className="page-with-sidebar">
      <ChatUI
        title="Weather Agent"
        description="Multi-turn chat with tool-calling. Migrated to useGenkitAgent (v2 events + continuationId)."
        suggestions={[
          'What is the weather like in London?',
          'Is it sunny in Tokyo right now?',
          'Compare the weather in Paris and New York.',
        ]}
        messages={[...chatMessages, ...inFlightRows]}
        streamingText={agent.streamingText}
        loading={agent.phase === 'streaming'}
        onSend={handleSend}
        headerAction={
          agent.snapshotId ? (
            <Link to="/weather" className="btn btn-new-session" reloadDocument>
              ✨ New Session
            </Link>
          ) : null
        }
      />

      <aside className="info-sidebar">
        <h3>📋 v2 Migration</h3>
        <ol>
          <li>
            <code>useGenkitAgent</code> owns the streamFlow connection, the
            chunk dispatch, and the continuation-token round-trip.
          </li>
          <li>
            On mount, if a snapshotId is in the URL, the hook calls{' '}
            <code>/state</code> and rehydrates messages + custom state +
            artifacts.
          </li>
          <li>
            On every turn, the hook walks the v2 <code>event</code> field on
            each chunk (via <code>walkAgentEvent</code>) and surfaces{' '}
            <code>streamingText</code>, <code>toolCalls</code>,{' '}
            <code>pendingInterrupt</code>, etc. as reactive React state.
          </li>
          <li>
            The single opaque <code>continuationId</code> replaces the
            state-vs-snapshotId fork from v1.
          </li>
        </ol>

        <h4>Page code</h4>
        <pre>{`const agent = useGenkitAgent({
  url: '/api/weatherAgent',
  resumeFromContinuation,
});

agent.submit({ messages: [...] });
agent.streamingText;       // live tokens
agent.toolCalls;           // tool lifecycle
agent.messages;            // committed
agent.continuationId;      // bookmark this
agent.pendingInterrupt;    // user input needed
agent.respondToInterrupt(out);`}</pre>
      </aside>
    </div>
  );
}

function messageToChatRows(msg: {
  role: string;
  content?: any[];
}): ChatMessage[] {
  const rows: ChatMessage[] = [];
  const textParts: string[] = [];
  for (const p of msg.content ?? []) {
    if (p.text) textParts.push(p.text);
    if (p.toolRequest) {
      rows.push({
        role: 'tool',
        text: `🔧 ${p.toolRequest.name}(${JSON.stringify(p.toolRequest.input)})`,
      });
    }
    if (p.toolResponse) {
      rows.push({
        role: 'tool',
        text: `✅ ${p.toolResponse.name} → ${JSON.stringify(p.toolResponse.output)}`,
      });
    }
  }
  if (textParts.length > 0) {
    rows.unshift({
      role: msg.role as ChatMessage['role'],
      text: textParts.join(''),
    });
  }
  return rows;
}
